import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tealBackend.settings")
django.setup()

from rest_framework_simplejwt.tokens import AccessToken
token = AccessToken('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMjM1MDUzLCJpYXQiOjE3MzIyMzE0NTMsImp0aSI6IjI3YWUwY2ZlYmQ5MzQ4YjBhYzMzMzFiM2Q5ODRlZTA2IiwidXNlcl9pZCI6Imh0dHBzOi8vc29jaWFsLWRpc3RyaWJ1dGlvbi0xLTNhZGI4NGYxMjBkOS5oZXJva3VhcHAuY29tL2F1dGhvcnMvODkxMWE3MzItMjcyNy00M2UwLTk2OWEtZjM2N2M3NTk2NGU1In0._RkEwfTTZZLhOc7zIylROMCvQkW7JmcsMilTkTcDEjk')
print(token.payload)