# Generated by Django 5.1.2 on 2024-10-19 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, unique=True)),
                ('type', models.CharField(default='author', max_length=10)),
                ('host', models.URLField(default='http://localhost:8000/')),
                ('displayName', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('profileImage', models.URLField(blank=True, default='https://via.placeholder.com/150', null=True)),
                ('page', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
