# Generated by Django 5.1.2 on 2024-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "type",
                    models.CharField(default="author", editable=False, max_length=6),
                ),
                ("id", models.URLField(primary_key=True, serialize=False)),
                ("host", models.URLField()),
                ("displayName", models.CharField(max_length=255)),
                ("github", models.URLField()),
                ("profileImage", models.URLField()),
                ("page", models.URLField()),
            ],
        ),
    ]
