# Generated by Django 5.1.2 on 2024-11-02 21:36
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='page',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
