# Generated by Django 5.1.2 on 2024-11-17 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='inbox_comments', to='backendApp.comment')),
                ('follow_requests', models.ManyToManyField(blank=True, related_name='inbox_follows', to='backendApp.followrequest')),
                ('likes', models.ManyToManyField(blank=True, related_name='inbox_likes', to='backendApp.like')),
                ('posts', models.ManyToManyField(blank=True, related_name='inbox_posts', to='backendApp.post')),
            ],
        ),
    ]
