# Generated by Django 4.2 on 2024-11-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://teal-rakshit-a972530cc317.herokuapp.com/'),
        ),
    ]
