# Generated by Django 5.1.2 on 2024-11-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://social-distribution-1-3adb84f120d9.herokuapp.com/'),
        ),
    ]
