# Generated by Django 5.1.2 on 2024-11-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotenode',
            name='allow_inbound',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='allow_outbound',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='description',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='password',
        ),
        migrations.RemoveField(
            model_name='remotenode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='remotenode',
            name='_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
