# Generated by Django 5.1.2 on 2024-10-20 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='backendApp.author'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.URLField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='post', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('page', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('contentType', models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private'), ('INVISIBLE', 'Invisible')], max_length=10)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='backendApp.author')),
            ],
        ),
    ]
