# Generated by Django 5.1.2 on 2024-10-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.URLField(default='https://github.com/placeholder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='https://github.com/placeholder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='backendApp.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/plain', 'Plain Text'), ('text/markdown', 'Markdown'), ('image/png;base64', 'PNG Image (Base64)'), ('image/jpeg;base64', 'JPEG Image (Base64)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('PRIVATE', 'Private')], max_length=10),
        ),
    ]
