# Generated by Django 4.2 on 2024-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backendApp", "0002_alter_author_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="host",
            field=models.URLField(
                default="https://teal-pranav-0e8aa7849ad7.herokuapp.com/api/"
            ),
        ),
    ]
