# Generated by Django 4.2 on 2024-11-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_alter_author_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default='https://teal-darrenkrz-c0d7276a7808.herokuapp.com/'),
        ),
    ]
