# Generated by Django 5.1.2 on 2024-11-02 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_alter_author_id_alter_author_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
