# Generated by Django 5.1.2 on 2024-11-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_remove_remotenode_allow_inbound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='_password',
            field=models.TextField(),
        ),
    ]
