# Generated by Django 5.1.2 on 2024-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0002_alter_author_id_alter_author_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('INVISIBLE', 'Invisible')], max_length=10),
        ),
    ]
