# Generated by Django 4.2 on 2024-12-07 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_alter_author_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_repost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='repost_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reposted_by',
        ),
    ]
