# Generated by Django 5.1.2 on 2024-10-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_alter_author_id_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
