# Generated by Django 5.1.2 on 2024-10-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0003_post_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
