# Generated by Django 5.1.2 on 2024-11-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
