# Generated by Django 5.1.2 on 2024-11-03 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_alter_repost_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
