# Generated by Django 5.1.2 on 2024-10-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
